// TravellerExt.idl : TravellerExt 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(TravellerExt.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

    // ITravellerMenuExt Interface
    [
        object,
        uuid(1D16BFEE-C651-47C0-A5AA-B610B63D2B23),
        dual,
        nonextensible,
        helpstring("ITravellerMenuExt Interface"),
        pointer_default(unique)
    ]
    interface ITravellerMenuExt : IDispatch {};

    // ITravellerBgMenuExt Interface
    [
        object,
        uuid(EBBC8177-C739-4E36-A2DC-DAC4406AE236),
        dual,
        nonextensible,
        helpstring("ITravellerBgMenuExt Interface"),
        pointer_default(unique)
    ]
    interface ITravellerBgMenuExt : IDispatch {};

[
    uuid(86369FD7-46EA-45D3-A972-981B0B52A8AC),
    version(1.0),
    helpstring("TravellerExt 1.0 Type Library")
]
library TravellerExtLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    // TravellerMenuExt Class
    [
        uuid(66276779-39DB-40A5-8F32-BB36A2B8F698),
        helpstring("TravellerMenuExt Class")
    ]
    coclass TravellerMenuExt
    {
        [default] interface ITravellerMenuExt;
    };

    // TravellerBgMenuExt Class
    [
        uuid(086E6038-7710-4399-B85C-B89981E01D41),
        helpstring("TravellerBgMenuExt Class")
    ]
    coclass TravellerBgMenuExt
    {
        [default] interface ITravellerBgMenuExt;
    };
};
